vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        trick_picture:
            uri_prefix: /images/tricks_pictures
            upload_destination: '%kernel.project_dir%/public/images/tricks_pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
